spring:
  main:
    banner-mode: console
  jpa:
    show-sql: false
##############################################
# 日志及临时文件存储
##############################################
logging:
  file:
    path: logs
  level:
    root: warn
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-history: 30
      max-file-size: 10MB