spring:
  main:
    banner-mode: console
  jpa:
    show-sql: true
##############################################
# 日志及临时文件存储
##############################################
logging:
  file:
    path: target/logs
  level:
    root: info
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 1
      max-file-size: 2MB