#
# Copyright (C) 2017 优客服-多渠道客服系统
# Modifications copyright (C) 2018-2019 Chatopera Inc, <https://www.chatopera.com>
# Modifications copyright (C) 2021 Dely
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 如何加载配置文
# https://docs.spring.io/spring-boot/docs/1.5.6.RELEASE/reference/htmlsingle/
# https://stackoverflow.com/questions/35531661/using-env-variable-in-spring-boots-application-properties
spring:
  config:
    import: git.properties
  profiles:
    active: dev
  ##############################################
  # Artemis消息服务
  ##############################################
  artemis:
    mode: native
    user: artemis
    password: artemis
    pool:
      enabled: true
      max-connections: 50
    broker-url: tcp://localhost:61616
  ##############################################
  # Spring Data
  ##############################################
  data:
    elasticsearch:
      # suppress inspection "SpringBootApplicationProperties"
#      properties:
#        index:
#          max_result_window: 100000
#        path:
#          data: ../data
      repositories:
        enabled: true
    jpa:
      repositories:
        enabled: true
    redis:
      repositories:
        enabled: false
  ##############################################
  # 数据源
  ##############################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall,slf4j
      # 初始化大小
      initial-size: 5
      # 最大
      max-active: 100
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 100000
      # 最小
      min-idle: 5
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow:
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/druid2/*"
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cosinee?useUnicode=true&characterEncoding=UTF-8
    username: root
  # Elasticsearch
  elasticsearch:
    uris: http://localhost:9200
  ##############################################
  # FREEMARKER (FreeMarkerAutoConfiguration)
  ##############################################
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    settings:
      classic_compatible: true
      default_encoding: UTF-8
      number_format: 0.###
      output_format: HTMLOutputFormat
      template_update_delay: 0
      url_escaping_charset: UTF-8
    suffix: .ftlh
    template-loader-path:
      - classpath:/templates/
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: false
  ##############################################
  # Redis Connection
  ##############################################
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: localhost
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 20
    # Redis服务器连接密码（默认为空）
    password: ''
    # Redis服务器连接端口
    port: 6379
    session:
      db: 1
      # 连接超时时间（毫秒），因为客服启动时
      # 占用比较大的时间，此处timeout值必须设置为0才能正常启动
    timeout: 100s
    token:
      db: 3
  session:
    store-type: redis
  servlet:
    multipart:
      # 文件上传限制
      enabled: true
      max-file-size: 20MB
      max-request-size: 21MB
      location: &path ../data

# suppress inspection "SpringBootApplicationProperties" for whole file
# 在集群状态下，每个Node都有自己唯一的ID
application:
  build:
    datestr: PLACEHOLDER
  customer:
    entity: Trial
  node:
    id: localhost
  # cookie加密
  security:
    password: cskefu

##############################################
# 企业聊天机器人
##############################################
bot:
  baseurl: https://bot.chatopera.com
ads:
  login:
    banner: placeholder

##############################################
# Cache
##############################################
## Available create_by_force, skip
cache:
  setup:
    strategy: create_by_force

##############################################
# Skype渠道集成配置
##############################################
# 从外部系统获得 SkypeID对应的联系人信息
channel:
  skype:
    crm: ''

cs:
  im:
    server:
      ssl:
        port: ''

cskefu:
  callout:
    watch:
      ##############################################
      # Callout Settings
      ##############################################
      # Loop Interval
      interval: 60000
  settings:
    webim:
      ##############################################
      # 业务功能相关设置
      ##############################################
      # 是否开启渠道访客独立
      visitor-separate: false
endpoints:
  prometheus:
    enabled: true

##############################################
# Actuator 监控数据采集
# https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/html/production-ready-endpoints.html
##############################################
management:
  endpoint:
    auditevents:
      enabled: false
    beans:
      enabled: false
    conditions:
      enabled: false
    configprops:
      enabled: false
    env:
      enabled: false
    health:
      enabled: true
    httptrace:
      enabled: false
    info:
      enabled: true
    loggers:
      enabled: false
    mappings:
      enabled: false
    metrics:
      enabled: true
    shutdown:
      enabled: false
  server:
    base-path: /actuator

##############################################
# 服务端口
##############################################
# server
server:
  connection:
    max: 2000
  port: 8035
  servlet:
    context-path: /
    session:
      cookie:
        max-age: &timeout 30m
        http-only: true
      timeout: *timeout
  session-timeout: 86400
  threads:
    # The maximum number of request processing threads to be created by this Connector
    max: 2000
  tomcat:
    # Setting max size of post requests to 100MB
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
    threads:
      max: 400
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for

##############################################
# 百度统计 Key
# https://tongji.baidu.com/
# 汇总使用情况：登录，打开页面，etc.
# 登录 -> 管理 -> 新增网站 -> 代码获取 -> 拷贝SiteKey
# hm.src = "https://hm.baidu.com/hm.js?YOUR_SITE_KEY";
# 加入后在百度统计内点击：代码安装检查，代码检查成功表示安装成功；注意网站域名等一致，数据收集有延迟。
##############################################
tongji:
  baidu:
    sitekey: ''

# IM Server
uk:
  im:
    server:
      host: localhost
      port: 8036
      threads: 1000

##############################################
# 临时文件存储
##############################################
web:
  upload-path: *path
