/*
 * Project version information. Generated - do not modify.
 */
package mondrian.server;
/**
 * Version information for Mondrian. (Generated by build)
 */
class MondrianServerVersion {
    static final String VENDOR = "Pentaho";
    static final String NAME = "mondrian";
    static final String VERSION = "3.14.0.0-12";
    static final int MAJOR_VERSION = 3;
    static final int MINOR_VERSION = 130;
    static final String COPYRIGHT_YEAR = "2017";
}
// End MondrianServerVersion.java